samba:
  image: dlip/raspbian-ansible-samba
  volumes:
    - /mnt/data:/srv/samba/shares/public
    # Dev Testing:
    - ./host_vars:/var/playbooks/host_vars
    - ./roles/dlip.samba:/var/playbooks/roles/dlip.samba
  ports:
    - "445:445"
    - "139:139"
    - "137:137/udp"
    - "138:138/udp"
